name: Compile and deploy docs 📚
on:
  push:
    tags:
      - v*
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
      - name: Compile javadoc 🔧
        run: ./gradlew javadoc
      - name: Extract release ✂️
        shell: bash
        run: echo "##[set-output name=release;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_release
      - name: Deploy latest docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: static/javadoc/messaging
          git-config-name: Kryonite Labs Bot
          git-config-email: opensource@kryonite.org
          target-folder: latest
      - name: Deploy versioned docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: static/javadoc/messaging
          git-config-name: Kryonite Labs Bot
          git-config-email: opensource@kryonite.org
          target-folder: ${{ steps.extract_release.outputs.release }}