name: Compile and deploy docs 📚

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  compile-and-deploy-docs:
    uses: kryonitelabs/.github/.github/workflows/release-docs-to-pages.yaml@main
